import { StyleSheet } from 'react-native';
const SuccessColor = "#3b8132";
const PrimaryColor = "#1065c0";
const WarningColor = "#e47200";
const DangerColor = "#c61a09";

export default StyleSheet.create({
    containerCenter:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        marginHorizontal:20
    },
    Center:{
        alignItems:'center',
        width:'100%',
    },  
    Devider5:{
        marginVertical:5
    },
    Devider10:{
        marginVertical:10
    },
    textNormal:{
        fontFamily:'Poppins-Regular',
        fontSize:12,
        color:'black'
    },
    textNormalBold:{
        fontFamily:'Poppins-Bold',
        fontSize:12,
        color:'black',
        fontWeight:'bold'
    },
    textLarge:{
        fontFamily:'Poppins-Regular',
        fontSize:14,
        color:'black'
    },
    textLargeBold:{
        fontFamily:'Poppins-Bold',
        fontSize:14,
        color:'black',
        fontWeight:'bold'
    },
    B1:{
        fontFamily:'Poppins-Regular',
        fontSize:24,
        color:'black',
    },
    B1Bold:{
        fontFamily:'Poppins-Bold',
        fontSize:24,
        color:'black',
        fontWeight:'bold'
    },
    B2:{
        fontFamily:'Poppins-Regular',
        fontSize:20,
        color:'black',
    },
    B2Bold:{
        fontFamily:'Poppins-Bold',
        fontSize:20,
        color:'black',
        fontWeight:'bold'
    },
    B3:{
        fontFamily:'Poppins-Regular',
        fontSize:18,
        color:'black',
    },
    B3Bold:{
        fontFamily:'Poppins-Bold',
        fontSize:18,
        color:'black',
        fontWeight:'bold'
    },
    B4:{
        fontFamily:'Poppins-Regular',
        fontSize:16,
        color:'black',
    },
    B4Bold:{
        fontFamily:'Poppins-Bold',
        fontSize:16,
        color:'black',
        fontWeight:'bold'
    },
    BtnSuccess:{
        borderRadius:20,
        backgroundColor:SuccessColor,
        paddingVertical:10,
        alignItems:'center',
        width:'100%',
    },
    BtnPrimary:{
        borderRadius:20,
        backgroundColor:PrimaryColor,
        paddingVertical:10,
        alignItems:'center',
        width:'100%',
    },
    BtnWarning:{
        borderRadius:20,
        backgroundColor:WarningColor,
        paddingVertical:10,
        alignItems:'center',
        width:'100%',
    },
    BtnDanger:{
        borderRadius:20,
        backgroundColor:DangerColor,
        paddingVertical:10,
        alignItems:'center',
        width:'100%',
    },
    TextBtnWhite:{
        fontFamily:'Poppins-Bold',
        fontSize:12,
        color:'white',
        fontWeight:'bold'
    },
    TextBtnWhiteLarge:{
        fontFamily:'Poppins-Bold',
        fontSize:14,
        color:'white',
        fontWeight:'bold'
    },
    Card:{
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        backgroundColor:'white',
        borderRadius:10,
        paddingHorizontal:20,
        paddingVertical:10,
        width:'100%'
    },
    BtnCircleSuccess:{
        width:50,
        height:50,
        borderRadius:25,
        backgroundColor:SuccessColor,
        alignItems:'center',
        justifyContent:'center'
    },
    InputBox:{
        borderWidth:0.5,
        borderRadius:10,
        paddingHorizontal:10,
        width:'100%'
    },
    InputBoxGroup:{
        borderWidth:0.5,
        borderRadius:10,
        paddingHorizontal:10,
        width:'100%',
        flexDirection:'row',
        alignItems:'center'
    },
    textInput:{
        fontFamily:'Poppins-Regular',
        fontSize:12,
        color:'black',
    },
    textInputGroup:{
        fontFamily:'Poppins-Regular',
        fontSize:12,
        color:'black',
        flex:1,
        marginLeft:5
    },
    ImageLarge:{
        width:150,
        height:150,
        resizeMode:'contain'
    },
})